#!/usr/bin/python3
print('Enter the first letter of your name:')
letter_of_name = input()
letter_of_name = letter_of_name.capitalize()
print('Enter the first letter of your last name:')
letter_of_surname = input()
letter_of_surname = letter_of_surname.capitalize()
name = {'A': 'Captain',
'B': 'Super',
'C': 'Doctor',
'D': 'The Phantom',
'E': 'Ultra',
'F': 'Amazing',
'G': 'Lightning',
'H': 'Giant',
'I': 'Razor',
'J': 'Steel',
'K': 'Ghost',
'L': 'Secret agent',
'M': 'Agent',
'N': 'Kinetic',
'O': 'Black',
'P': 'The Great',
'Q': 'Major',
'R': 'Professor',
'S': 'Mighty',
'T': 'Crimson',
'U': 'Tough',
'V': 'Iron', 
'W': 'Thunder',
'X': 'The Flying',
'Y': 'Wonder',
'Z': 'Space'}
surname = {'A': 'Gem',
'B': 'Hornet',
'C': 'Wolf',
'D': 'Storm',
'E': 'Master',
'F': 'Cobra',
'G': 'Brain',
'H': 'Knight',
'I': 'Claw',
'J': 'Beast',
'K': 'Master',
'L': 'Viper',
'M': 'Edge',
'N': 'Blaze',
'O': 'Fang',
'P': 'Falcon',
'Q': 'Soldier',
'R': 'Avenger',
'S': 'Wing',
'T': 'Justice',
'U': 'Machine',
'V': 'Guard',
'W': 'Ninja',
'X': 'Arrow',
'Y': 'Ranger',
'Z': 'Ivy',}
print('You are', name[letter_of_name], surname[letter_of_surname])
# :)
